name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Copy Docker Compose files to Azure VM
      run: |
        sshpass -p ${{ secrets.AZURE_SSH_PASSWORD }} scp -r ./docker-compose.yml ./retail-inventory ./screenshots ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }}:/home/${{ secrets.AZURE_USERNAME }}/app

    - name: SSH into Azure VM and deploy
      run: |
        sshpass -p ${{ secrets.AZURE_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }} << 'EOF'
          cd /home/${{ secrets.AZURE_USERNAME }}/app
          docker-compose down
          docker-compose up -d
        EOF
