name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_PASSWORD }}

    - name: Copy Docker Compose files to Azure VM
      run: |
        scp -r ./docker-compose.yml ./retail-inventory ./screenshots ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }}:/home/${{ secrets.AZURE_USERNAME }}/app

    - name: SSH into Azure VM and deploy
      run: |
        ssh ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_HOST }} << 'EOF'
          cd /home/${{ secrets.AZURE_USERNAME }}/app
          docker-compose down
          docker-compose up -d
        EOF
